image: alpine:3.19

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  default:
    - step:
        name: Build & Test
        script:
          - apk add --no-cache nodejs npm
          - cd app && npm ci
          - npm run build
          - echo "✅ Basic pipeline passed"

  branches:
    hardened/**:
      - step:
          name: Security Gates
          services:
            - docker
          caches:
            - docker
          script:
            # Install dependencies
            - apk add --no-cache bash git nodejs npm docker-cli jq python3 py3-pip
            - pip3 install checkov semgrep
            
            # Install Trivy
            - wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
            
            # Install Syft
            - wget -qO- https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
            
            # Make scripts executable
            - chmod +x scripts/*.sh
            
            # Set security thresholds
            - export SAST_MAX_HIGH=0 SAST_MAX_MEDIUM=0
            - export SCA_MAX_HIGH=0 IMG_MAX_HIGH=0
            
            # Run security checks
            - ./scripts/scan_secrets.sh
            - ./scripts/scan_sast.sh
            - ./scripts/scan_sca.sh
            
            # Build and scan container
            - cd app && docker build -t build-breaker:workshop .
            - cd .. && ./scripts/scan_iac.sh
            - ./scripts/scan_container.sh
            - ./scripts/make_sbom.sh
            - ./scripts/verify_sign.sh
